Repository kir-dev/pek-next, pull requests merged in 2020-04, with the labels that each got.

#210 Move EvaluationControllerTest to rspec
  spec/requests/evalutations_controller_spec.rb
  test/controllers/evaluations_controller_test.rb
Labels: refactor

#213 Fix join group button margin
  app/decorators/membership_view_model_decorator.rb
Labels: UI / UX

#214 Update resort leader permissions
  app/controllers/entry_requests_controller.rb
  app/controllers/point_details_controller.rb
Labels: enhancement

#221 Improve joining a group
  app/controllers/memberships_controller.rb
  app/models/concerns/notifications/membership_notifier.rb
  app/services/create_membership.rb
  app/services/membership/create_service.rb
  spec/requests/memberships_controller_spec.rb
  spec/services/membership/create_service_spec.rb
Labels: refactor

#228 Determine rails env for building assets in Dockerfile
  Dockerfile
Labels: bug

#229 Fix typo in production config
  config/environments/production.rb
Labels: bug

#232 Fix deprecated parameter style in spec files
  config/initializers/monkey_patches.rb
  spec/requests/post_type_controller_spec.rb
  spec/requests/profiles_controller_spec.rb
Labels: refactor
