Repository kir-dev/pek-next, pull requests merged in 2020-03, with the labels that each got.

#152 Remove fixtures from rspec runs
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
  spec/support/initializers/database_cleaner.rb
  test/factories/groups.rb
  test/factories/post_types.rb
Labels: tech-debt

#134 Improve test coverage
  spec/rails_helper.rb
  spec/requests/auth_sch_services_spec.rb
  spec/support/helpers/authentication_helper.rb
  spec/support/helpers/request_helpers.rb
  test/controllers/auth_sch_services_controller_test.rb
  test/factories/evaulations.rb
  test/factories/users.rb
  test/test_helper.rb
Labels: help wanted

#157 Remove mocha gem
  Gemfile
  Gemfile.lock
  test/models/group_test.rb
  test/test_helper.rb
Labels: tech-debt

#156 Show member counters
  app/decorators/membership_view_model_decorator.rb
  app/helpers/groups_helper.rb
  app/views/groups/show.html.erb
Labels: enhancement

#142 Add ability to delete a group's post type
  app/controllers/post_types_controller.rb
  app/decorators/membership_view_model_decorator.rb
  app/models/post_type.rb
  app/views/groups/show.html.erb
  app/views/post_types/index.html.erb
  config/routes.rb
  spec/requests/post_type_controller_spec.rb
  test/controllers/post_types_controller_test.rb
Labels: enhancement

#159 Move common post types from memberships to post_type
  app/models/membership.rb
  app/models/post.rb
  app/models/post_type.rb
  app/services/create_membership.rb
  app/services/create_post.rb
  app/services/destroy_post.rb
  db/seeds.rb
  lib/tasks/migration.rake
  spec/requests/post_type_controller_spec.rb
  test/factories/post_types.rb
  test/factories/posts.rb
Labels: refactor

#160 Migrate profiles controller tests to rspec
  spec/requests/profiles_controller_spec.rb
  test/controllers/profiles_controller_test.rb
Labels: refactor
